-- =============================================================================
-- BL_DM — NovaTech Business Layer Dimensional Model (Star Schema)
-- =============================================================================
-- This is a BONUS script, not explicitly required by the Task 4 brief (which
-- only asks for a DIM_DATES script) — provided so every table in chapter "3
-- Business Layer Dimensional Model" of the Business Template has a physical,
-- ready-to-run definition, the same way BL_3NF.* was eventually scripted.
--
-- Conventions applied throughout (see Naming_Conventions.docx):
--   - DIM_<Name in Plural>            Type 1 / Type 0 dimensions
--   - DIM_<Name in Plural>_SCD        Type 2 dimension (history tracked)
--   - FCT_<Name in Plural>_<Level>    fact table, level = DD (daily grain)
--   - <Name>_SURR_ID                  surrogate PK, generated by SEQUENCE (never SERIAL)
--   - <Name>_SRC_ID + SOURCE_SYSTEM + SOURCE_TABLE   obligatory source triplet
--   - INSERT_DT / UPDATE_DT           obligatory technical columns
--   - NOT NULL on every column except KPIs and the channel-specific
--     attributes that are genuinely inapplicable to one half of a conformed
--     dimension (flagged inline below) — the same documented exception
--     BL_3NF.CE_CUSTOMERS_SCD already uses for the identical reason.
--   - DEFAULT, UNIQUE and CHECK constraints are not used anywhere in this
--     model, mirroring the choice already made for BL_3NF.
--   - Default ("Not Applicable") rows use SURR_ID = 0, matching the
--     convention already chosen for this project at the BL_3NF layer,
--     instead of the Naming Conventions doc's generic -1 example.
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS BL_DM;

DROP TABLE IF EXISTS BL_DM.FCT_SALES_DD;
DROP TABLE IF EXISTS BL_DM.DIM_PRODUCTS;
DROP TABLE IF EXISTS BL_DM.DIM_CUSTOMERS_SCD;
DROP TABLE IF EXISTS BL_DM.DIM_EMPLOYEES;
DROP TABLE IF EXISTS BL_DM.DIM_CHANNELS;
DROP TABLE IF EXISTS BL_DM.DIM_PAYMENT_METHODS;
DROP TABLE IF EXISTS BL_DM.DIM_SHIPPING_TYPES;
DROP TABLE IF EXISTS BL_DM.DIM_PAYMENT_TERMS;

DROP SEQUENCE IF EXISTS BL_DM.SEQ_PRODUCT_SURR_ID;
DROP SEQUENCE IF EXISTS BL_DM.SEQ_CUSTOMER_SURR_ID;
DROP SEQUENCE IF EXISTS BL_DM.SEQ_EMPLOYEE_SURR_ID;
DROP SEQUENCE IF EXISTS BL_DM.SEQ_CHANNEL_SURR_ID;
DROP SEQUENCE IF EXISTS BL_DM.SEQ_PAYMENT_METHOD_SURR_ID;
DROP SEQUENCE IF EXISTS BL_DM.SEQ_SHIPPING_TYPE_SURR_ID;
DROP SEQUENCE IF EXISTS BL_DM.SEQ_PAYMENT_TERMS_SURR_ID;

CREATE SEQUENCE BL_DM.SEQ_PRODUCT_SURR_ID START WITH 1;
CREATE SEQUENCE BL_DM.SEQ_CUSTOMER_SURR_ID START WITH 1;
CREATE SEQUENCE BL_DM.SEQ_EMPLOYEE_SURR_ID START WITH 1;
CREATE SEQUENCE BL_DM.SEQ_CHANNEL_SURR_ID START WITH 1;
CREATE SEQUENCE BL_DM.SEQ_PAYMENT_METHOD_SURR_ID START WITH 1;
CREATE SEQUENCE BL_DM.SEQ_SHIPPING_TYPE_SURR_ID START WITH 1;
CREATE SEQUENCE BL_DM.SEQ_PAYMENT_TERMS_SURR_ID START WITH 1;

-- =============================================================================
-- DIM_PRODUCTS  (Type 1 — overwrite; one row per SKU, conformed across B2C/B2B)
-- Hierarchy flattened from BL_3NF.CE_PRODUCTS -> CE_PRODUCT_TYPES ->
-- CE_PRODUCT_CATEGORIES into this single denormalized dimension, per
-- Naming Conventions' "Hierarchy on DM Layer" rule.
-- =============================================================================
CREATE TABLE BL_DM.DIM_PRODUCTS (
    PRODUCT_SURR_ID          BIGINT        NOT NULL,   -- PK, by sequence
    PRODUCT_SRC_ID           VARCHAR(20)   NOT NULL,    -- NK = SKU, shared by both source systems
    PRODUCT_TYPE_ID          INT           NOT NULL,    -- hierarchy level 2 (from CE_PRODUCT_TYPES)
    PRODUCT_TYPE_NAME        VARCHAR(50)   NOT NULL,
    PRODUCT_CATEGORY_ID      INT           NOT NULL,    -- hierarchy level 1, top (from CE_PRODUCT_CATEGORIES)
    PRODUCT_CATEGORY_NAME    VARCHAR(50)   NOT NULL,
    BRAND                    VARCHAR(50)   NOT NULL,
    WARRANTY_PERIOD_MONTHS   INT           NOT NULL,    -- B2C retail context; populated for every SKU (see chapter narrative)
    LAUNCH_YEAR              INT           NOT NULL,
    PRODUCT_STATUS           VARCHAR(20)   NOT NULL,
    BULK_PACKAGING_UNIT      VARCHAR(50)   NOT NULL,    -- B2B wholesale context; populated for every SKU
    MINIMUM_ORDER_QUANTITY   INT           NOT NULL,
    INSERT_DT                DATE          NOT NULL,
    UPDATE_DT                DATE          NOT NULL,
    SOURCE_SYSTEM            VARCHAR(60)   NOT NULL,
    SOURCE_TABLE             VARCHAR(60)   NOT NULL,
    CONSTRAINT PK_DIM_PRODUCTS PRIMARY KEY (PRODUCT_SURR_ID)
);

-- =============================================================================
-- DIM_CUSTOMERS_SCD  (Type 2 — account_tier and loyalty_member tracked)
-- Carries Country/City as a flattened geography hierarchy, same treatment
-- as Product above. PK is a single fresh SURR_ID per version, NOT the
-- (customer_id, start_dt) composite used at the BL_3NF layer — Naming
-- Conventions, "Rules for Facts table" #2: "As PK for SCD2 table on DM - ID
-- only."
-- =============================================================================
CREATE TABLE BL_DM.DIM_CUSTOMERS_SCD (
    CUSTOMER_SURR_ID     BIGINT        NOT NULL,   -- PK; a NEW value is generated for every version
    CUSTOMER_SRC_ID      VARCHAR(20)   NOT NULL,    -- NK; durable, same value across every version of one customer
    CUSTOMER_TYPE        VARCHAR(10)   NOT NULL,    -- 'Individual' (B2C) or 'Business' (B2B)
    CUSTOMER_NAME        VARCHAR(255),               -- Business only (NULL for Individual rows)
    DATE_OF_BIRTH        DATE,                       -- Individual only
    GENDER               VARCHAR(10),                -- Individual only
    LOYALTY_MEMBER       VARCHAR(5),                 -- Individual only; SCD2-tracked attribute
    CUSTOMER_SEGMENT     VARCHAR(20),                -- Individual only
    INDUSTRY             VARCHAR(50),                -- Business only
    ACCOUNT_TIER         VARCHAR(10),                -- Business only; SCD2-tracked attribute
    COMPANY_SIZE         VARCHAR(20),                -- Business only
    ONBOARDING_DATE      DATE,                       -- Business only
    CREDIT_LIMIT         NUMERIC(12,2),               -- Business only
    APPROVER_NAME        VARCHAR(255),               -- Business only
    BUDGET_CODE          VARCHAR(20),                -- Business only
    CITY_ID              BIGINT        NOT NULL,    -- geography hierarchy level 2 (from CE_CITIES)
    CITY_NAME            VARCHAR(100)  NOT NULL,
    COUNTRY_ID           INT           NOT NULL,    -- geography hierarchy level 1, top (from CE_COUNTRIES)
    COUNTRY_NAME         VARCHAR(100)  NOT NULL,
    START_DT             DATE          NOT NULL,
    END_DT               DATE,                       -- NULL = currently open/active version (no sentinel default; mirrors BL_3NF)
    IS_ACTIVE            VARCHAR(1)    NOT NULL,    -- 'Y' / 'N'
    INSERT_DT            DATE          NOT NULL,
    SOURCE_SYSTEM        VARCHAR(60)   NOT NULL,
    SOURCE_TABLE         VARCHAR(60)   NOT NULL,
    CONSTRAINT PK_DIM_CUSTOMERS_SCD PRIMARY KEY (CUSTOMER_SURR_ID)
    -- No UPDATE_DT: a change is always captured as a new row (see Naming
    -- Conventions SCD2 rules); same exception already used on BL_3NF.CE_CUSTOMERS_SCD.
);

-- =============================================================================
-- DIM_EMPLOYEES (Type 1). Includes the dedicated "Not Applicable" member
-- used by every B2C fact row (B2C has no account manager).
-- =============================================================================
CREATE TABLE BL_DM.DIM_EMPLOYEES (
    EMPLOYEE_SURR_ID     BIGINT        NOT NULL,   -- PK
    EMPLOYEE_SRC_ID      VARCHAR(20)   NOT NULL,    -- NK ('0' for the N/A row)
    EMPLOYEE_NAME        VARCHAR(255)  NOT NULL,
    DEPARTMENT           VARCHAR(50)   NOT NULL,
    REGION_ASSIGNED      VARCHAR(50)   NOT NULL,
    HIRE_DATE            DATE          NOT NULL,
    EMAIL                VARCHAR(255)  NOT NULL,
    SALES_QUOTA          NUMERIC(12,2) NOT NULL,
    PERFORMANCE_TIER     VARCHAR(20)   NOT NULL,
    INSERT_DT            DATE          NOT NULL,
    UPDATE_DT            DATE          NOT NULL,
    SOURCE_SYSTEM        VARCHAR(60)   NOT NULL,
    SOURCE_TABLE         VARCHAR(60)   NOT NULL,
    CONSTRAINT PK_DIM_EMPLOYEES PRIMARY KEY (EMPLOYEE_SURR_ID)
);

INSERT INTO BL_DM.DIM_EMPLOYEES VALUES (
    0, '0', 'Not Applicable', 'n.a.', 'n.a.', '1990-01-01', 'n.a.', 0, 'n.a.',
    CURRENT_DATE, CURRENT_DATE, 'MANUAL', 'MANUAL'
);

-- =============================================================================
-- DIM_CHANNELS (Type 0 — never changes; built entirely by the ETL system)
-- =============================================================================
CREATE TABLE BL_DM.DIM_CHANNELS (
    CHANNEL_SURR_ID            INT          NOT NULL,   -- PK
    CHANNEL_SRC_ID             VARCHAR(10)  NOT NULL,    -- NK
    CHANNEL_NAME               VARCHAR(10)  NOT NULL,    -- 'B2C' / 'B2B'
    ORIGINATING_SYSTEM_NAME    VARCHAR(60)  NOT NULL,    -- e.g. 'NovaTech Direct' (business attribute - distinct from the technical SOURCE_SYSTEM triplet column below)
    INSERT_DT                  DATE         NOT NULL,
    UPDATE_DT                  DATE         NOT NULL,
    SOURCE_SYSTEM              VARCHAR(60)  NOT NULL,    -- ='MANUAL' (technical source triplet)
    SOURCE_TABLE               VARCHAR(60)  NOT NULL,
    CONSTRAINT PK_DIM_CHANNELS PRIMARY KEY (CHANNEL_SURR_ID)
);

INSERT INTO BL_DM.DIM_CHANNELS VALUES
    (1, '1', 'B2C', 'NovaTech Direct',            CURRENT_DATE, CURRENT_DATE, 'MANUAL', 'MANUAL'),
    (2, '2', 'B2B', 'NovaTech Business Solutions', CURRENT_DATE, CURRENT_DATE, 'MANUAL', 'MANUAL');

-- =============================================================================
-- DIM_PAYMENT_METHODS (Type 1, B2C only). Includes "Not Applicable" member
-- used by every B2B fact row (B2B settles on Payment Terms / invoicing).
-- =============================================================================
CREATE TABLE BL_DM.DIM_PAYMENT_METHODS (
    PAYMENT_METHOD_SURR_ID   INT           NOT NULL,   -- PK
    PAYMENT_METHOD_SRC_ID    VARCHAR(20)   NOT NULL,    -- NK
    PAYMENT_METHOD_NAME      VARCHAR(20)   NOT NULL,
    PAYMENT_CHANNEL_TYPE     VARCHAR(20),                -- NULL on the N/A row only
    PROCESSING_FEE_PCT       NUMERIC(5,2),
    SETTLEMENT_PERIOD_DAYS   INT,
    REFUNDABLE_FLAG          VARCHAR(5),
    CURRENCY_ACCEPTED        VARCHAR(5),
    MINIMUM_TXN_AMOUNT       NUMERIC(10,2),
    AVAILABILITY_CHANNEL     VARCHAR(30),
    INSERT_DT                DATE          NOT NULL,
    UPDATE_DT                DATE          NOT NULL,
    SOURCE_SYSTEM            VARCHAR(60)   NOT NULL,
    SOURCE_TABLE             VARCHAR(60)   NOT NULL,
    CONSTRAINT PK_DIM_PAYMENT_METHODS PRIMARY KEY (PAYMENT_METHOD_SURR_ID)
);

INSERT INTO BL_DM.DIM_PAYMENT_METHODS VALUES
    (0, '0', 'Not Applicable', NULL, NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_DATE, CURRENT_DATE, 'MANUAL', 'MANUAL'),
    (1, '1', 'Credit Card',  'Card',    2.9, 1, 'Yes', 'USD',  1.00, 'Online & In-Store', CURRENT_DATE, CURRENT_DATE, 'MANUAL', 'MANUAL'),
    (2, '2', 'Debit Card',   'Card',    1.5, 1, 'Yes', 'USD',  1.00, 'Online & In-Store', CURRENT_DATE, CURRENT_DATE, 'MANUAL', 'MANUAL'),
    (3, '3', 'Bank Transfer','Bank',    0.5, 2, 'Yes', 'USD', 50.00, 'Online Only',       CURRENT_DATE, CURRENT_DATE, 'MANUAL', 'MANUAL'),
    (4, '4', 'Cash',         'Cash',    0.0, 0, 'No',  'USD',  1.00, 'In-Store Only',     CURRENT_DATE, CURRENT_DATE, 'MANUAL', 'MANUAL'),
    (5, '5', 'PayPal',       'Digital', 3.4, 1, 'Yes', 'USD',  1.00, 'Online Only',       CURRENT_DATE, CURRENT_DATE, 'MANUAL', 'MANUAL');

-- =============================================================================
-- DIM_SHIPPING_TYPES (Type 1, B2C only). Includes "Not Applicable" member
-- used by every B2B fact row.
-- =============================================================================
CREATE TABLE BL_DM.DIM_SHIPPING_TYPES (
    SHIPPING_TYPE_SURR_ID         INT          NOT NULL,   -- PK
    SHIPPING_TYPE_SRC_ID          VARCHAR(20)  NOT NULL,    -- NK
    SHIPPING_TYPE_NAME            VARCHAR(20)  NOT NULL,
    SHIPPING_CARRIER               VARCHAR(30),
    ESTIMATED_DELIVERY_DAYS        VARCHAR(10),
    SHIPPING_COST_TIER             VARCHAR(10),
    FREE_SHIPPING_ELIGIBLE_FLAG    VARCHAR(5),
    TRACKING_AVAILABLE_FLAG        VARCHAR(5),
    MAX_PACKAGE_WEIGHT_KG          INT,
    INTL_SHIPPING_AVAILABLE_FLAG   VARCHAR(5),
    INSERT_DT                      DATE         NOT NULL,
    UPDATE_DT                      DATE         NOT NULL,
    SOURCE_SYSTEM                  VARCHAR(60)  NOT NULL,
    SOURCE_TABLE                   VARCHAR(60)  NOT NULL,
    CONSTRAINT PK_DIM_SHIPPING_TYPES PRIMARY KEY (SHIPPING_TYPE_SURR_ID)
);

INSERT INTO BL_DM.DIM_SHIPPING_TYPES VALUES
    (0, '0', 'Not Applicable', NULL, NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_DATE, CURRENT_DATE, 'MANUAL', 'MANUAL'),
    (1, '1', 'Standard',  'RegionalPost',  '5-7', 'Low',    'No',  'Yes', 20, 'No',  CURRENT_DATE, CURRENT_DATE, 'MANUAL', 'MANUAL'),
    (2, '2', 'Expedited', 'RegionalPost',  '3-4', 'Medium', 'No',  'Yes', 20, 'No',  CURRENT_DATE, CURRENT_DATE, 'MANUAL', 'MANUAL'),
    (3, '3', 'Express',   'GlobalExpress', '2',   'High',   'Yes', 'Yes', 30, 'Yes', CURRENT_DATE, CURRENT_DATE, 'MANUAL', 'MANUAL'),
    (4, '4', 'Same Day',  'LocalCourier',  '0-1', 'High',   'No',  'Yes', 15, 'No',  CURRENT_DATE, CURRENT_DATE, 'MANUAL', 'MANUAL'),
    (5, '5', 'Overnight', 'GlobalExpress', '1',   'High',   'Yes', 'Yes', 30, 'Yes', CURRENT_DATE, CURRENT_DATE, 'MANUAL', 'MANUAL');

-- =============================================================================
-- DIM_PAYMENT_TERMS (Type 1, B2B only). Includes "Not Applicable" member
-- used by every B2C fact row.
-- =============================================================================
CREATE TABLE BL_DM.DIM_PAYMENT_TERMS (
    PAYMENT_TERMS_SURR_ID       INT          NOT NULL,   -- PK
    PAYMENT_TERMS_SRC_ID        VARCHAR(20)  NOT NULL,    -- NK
    PAYMENT_TERMS_NAME          VARCHAR(10)  NOT NULL,
    PAYMENT_DUE_DAYS            INT,
    EARLY_PAYMENT_DISCOUNT_PCT  NUMERIC(5,2),
    LATE_PAYMENT_PENALTY_PCT    NUMERIC(5,2),
    CURRENCY                    VARCHAR(5),
    PREFERRED_PAYMENT_METHOD    VARCHAR(20),
    TERMS_EFFECTIVE_DATE        DATE,
    INSERT_DT                   DATE         NOT NULL,
    UPDATE_DT                   DATE         NOT NULL,
    SOURCE_SYSTEM               VARCHAR(60)  NOT NULL,
    SOURCE_TABLE                VARCHAR(60)  NOT NULL,
    CONSTRAINT PK_DIM_PAYMENT_TERMS PRIMARY KEY (PAYMENT_TERMS_SURR_ID)
);

INSERT INTO BL_DM.DIM_PAYMENT_TERMS VALUES
    (0, '0', 'N/A',     NULL, NULL, NULL, NULL,  NULL,             NULL,         CURRENT_DATE, CURRENT_DATE, 'MANUAL', 'MANUAL'),
    (1, '1', 'Net 30',  30,   1.0,  1.5,  'USD', 'Bank Transfer', '2023-01-01', CURRENT_DATE, CURRENT_DATE, 'MANUAL', 'MANUAL'),
    (2, '2', 'Net 60',  60,   0.5,  2.0,  'USD', 'Bank Transfer', '2023-01-01', CURRENT_DATE, CURRENT_DATE, 'MANUAL', 'MANUAL'),
    (3, '3', 'Net 90',  90,   0.0,  2.5,  'USD', 'Bank Transfer', '2023-01-01', CURRENT_DATE, CURRENT_DATE, 'MANUAL', 'MANUAL'),
    (4, '4', 'Prepaid', 0,    2.0,  0.0,  'USD', 'Wire Transfer', '2023-01-01', CURRENT_DATE, CURRENT_DATE, 'MANUAL', 'MANUAL');

-- =============================================================================
-- FCT_SALES_DD — transaction-grain fact table
-- Grain: one row per order line (one product, one customer/company, one
-- order, one date, one channel) — unchanged from the grain declared in
-- Business Template Section 1.5 / carried through BL_3NF.CE_SALES.
-- "_DD" = daily date grain (EVENT_DT holds a calendar day, not an
-- aggregated period), per Naming Conventions rule #15.
-- =============================================================================
CREATE TABLE BL_DM.FCT_SALES_DD (
    EVENT_DT                     DATE           NOT NULL,   -- FK -> DIM_DATES.DATE_KEY; the order date
    PRODUCT_SURR_ID               BIGINT         NOT NULL,   -- FK -> DIM_PRODUCTS
    CUSTOMER_SURR_ID               BIGINT         NOT NULL,   -- FK -> DIM_CUSTOMERS_SCD (logical only — no DB constraint for SCD2 dimensions, per Naming Conventions)
    EMPLOYEE_SURR_ID                BIGINT         NOT NULL,   -- FK -> DIM_EMPLOYEES (0 for B2C rows)
    CHANNEL_SURR_ID                  INT            NOT NULL,   -- FK -> DIM_CHANNELS
    PAYMENT_METHOD_SURR_ID            INT            NOT NULL,   -- FK -> DIM_PAYMENT_METHODS (0 for B2B rows)
    SHIPPING_TYPE_SURR_ID              INT            NOT NULL,   -- FK -> DIM_SHIPPING_TYPES (0 for B2B rows)
    PAYMENT_TERMS_SURR_ID               INT            NOT NULL,   -- FK -> DIM_PAYMENT_TERMS (0 for B2C rows)
    ORDER_ID                      BIGINT         NOT NULL,   -- degenerate dimension
    ORDER_STATUS                  VARCHAR(20)    NOT NULL,   -- degenerate dimension
    FCT_QUANTITY_UNT               INT            NOT NULL,
    FCT_UNIT_PRICE_AMT             NUMERIC(10,2)  NOT NULL,
    FCT_UNIT_COST_AMT              NUMERIC(10,2)  NOT NULL,
    FCT_SALES_AMT                  NUMERIC(12,2)  NOT NULL,
    FCT_COST_AMT                   NUMERIC(12,2)  NOT NULL,
    FCT_GROSS_MARGIN_AMT           NUMERIC(12,2)  NOT NULL,   -- CALCULATED: FCT_SALES_AMT - FCT_COST_AMT
    FCT_GROSS_MARGIN_PCT           NUMERIC(5,2)   NOT NULL,   -- CALCULATED: FCT_GROSS_MARGIN_AMT / FCT_SALES_AMT * 100
    RATING                        INT,                        -- B2C only
    FCT_ADD_ON_TOTAL_AMT           NUMERIC(10,2),              -- B2C only
    RETURN_OR_COMPLAINT_FLAG      VARCHAR(5),                 -- B2C only
    FEEDBACK_COMMENT              VARCHAR(255),               -- B2C only
    RESOLUTION_TIME_DAYS          INT,                        -- B2C only
    FCT_REFUND_AMOUNT_AMT          NUMERIC(10,2),              -- B2C only
    SUPPORT_CHANNEL_USED          VARCHAR(10),                -- B2C only
    ESCALATION_REQUIRED_FLAG      VARCHAR(5),                 -- B2C only
    PO_NUMBER                     VARCHAR(20),                -- B2B only (degenerate)
    PO_ISSUE_DATE                 DATE,                       -- B2B only
    REQUESTED_DELIVERY_DATE       DATE,                       -- B2B only
    APPROVAL_STATUS               VARCHAR(10),                -- B2B only
    PO_TYPE                       VARCHAR(10),                -- B2B only
    PO_VALUE_THRESHOLD_FLAG       VARCHAR(5),                 -- B2B only
    INSERT_DT                     DATE           NOT NULL
    -- No surrogate PK (per BL_3NF.CE_SALES precedent) and no UPDATE_DT
    -- (a transactional fact is never updated in place).
);

CREATE INDEX IX_FCT_SALES_DD_EVENT_DT       ON BL_DM.FCT_SALES_DD (EVENT_DT);
CREATE INDEX IX_FCT_SALES_DD_PRODUCT        ON BL_DM.FCT_SALES_DD (PRODUCT_SURR_ID);
CREATE INDEX IX_FCT_SALES_DD_CUSTOMER       ON BL_DM.FCT_SALES_DD (CUSTOMER_SURR_ID);
CREATE INDEX IX_FCT_SALES_DD_CHANNEL        ON BL_DM.FCT_SALES_DD (CHANNEL_SURR_ID);

-- Physical (enforced) FKs only where the referenced dimension is Type 1/0 --
-- never against an SCD2 dimension (Naming Conventions, "Rules for Facts
-- table" #2: creating an FK constraint against an SCD2 table is prohibited).
ALTER TABLE BL_DM.FCT_SALES_DD
    ADD CONSTRAINT FK_FCT_SALES_PRODUCT  FOREIGN KEY (PRODUCT_SURR_ID)        REFERENCES BL_DM.DIM_PRODUCTS (PRODUCT_SURR_ID),
    ADD CONSTRAINT FK_FCT_SALES_EMPLOYEE FOREIGN KEY (EMPLOYEE_SURR_ID)       REFERENCES BL_DM.DIM_EMPLOYEES (EMPLOYEE_SURR_ID),
    ADD CONSTRAINT FK_FCT_SALES_CHANNEL  FOREIGN KEY (CHANNEL_SURR_ID)        REFERENCES BL_DM.DIM_CHANNELS (CHANNEL_SURR_ID),
    ADD CONSTRAINT FK_FCT_SALES_PAYMTHD  FOREIGN KEY (PAYMENT_METHOD_SURR_ID) REFERENCES BL_DM.DIM_PAYMENT_METHODS (PAYMENT_METHOD_SURR_ID),
    ADD CONSTRAINT FK_FCT_SALES_SHIPTYP  FOREIGN KEY (SHIPPING_TYPE_SURR_ID)  REFERENCES BL_DM.DIM_SHIPPING_TYPES (SHIPPING_TYPE_SURR_ID),
    ADD CONSTRAINT FK_FCT_SALES_PAYTERM  FOREIGN KEY (PAYMENT_TERMS_SURR_ID)  REFERENCES BL_DM.DIM_PAYMENT_TERMS (PAYMENT_TERMS_SURR_ID);
-- CUSTOMER_SURR_ID -> DIM_CUSTOMERS_SCD and EVENT_DT -> DIM_DATES.DATE_KEY
-- are deliberately NOT enforced as DB constraints (SCD2 rule above; DIM_DATES
-- is created by a separate script and may not exist yet in every environment).
