-- =============================================================================
-- Business Layer 3NF (schema BL_3NF) — Physical structure
-- =============================================================================
--
-- Conventions applied throughout:
--   - Every <entity>_id surrogate key is generated by its own SEQUENCE
--     (never SERIAL), per Naming_Conventions.docx column rule #6.
--   - Every table (the obligatory source triplet): SOURCE_ID (the natural
--     key as it appears in the source), SOURCE_SYSTEM, SOURCE_TABLE.
--   - CE_CUSTOMERS_SCD is the one Type-2 entity: composite PK
--     (customer_id, start_dt), plus END_DT / IS_ACTIVE, no UPDATE_DT (a
--     change is a new row, not an in-place update) — Naming_Conventions.docx,
--     "rules for SCD TYPE 2", rule 5.
--   - CE_SALES carries every FK as NOT NULL (a "Not Applicable" default
--     row always exists on the channel-specific side that doesn't apply),
--     has no UPDATE_DT (a transactional fact is never updated in place),
--     and has NO physical FK against CE_CUSTOMERS_SCD — Naming_Conventions.
--     docx, "Rules for Facts table", rule 2: a DB FK constraint against an
--     SCD2 table is "strongly PROHIBITED"; that link is logical only.
--   - No DEFAULT, UNIQUE or CHECK constraints anywhere, consistent with the
--     BL_3NF diagram and every prior task in this project.
--   - CREATE TABLE IF NOT EXISTS / CREATE SEQUENCE IF NOT EXISTS throughout,
--     so the whole script is rerunnable against a schema that already has
--     these objects (the brief: "DDL script must be rerunnable and
--     reusable and execute without errors").
--   - FK constraints are declared inline inside the CREATE TABLE IF NOT
--     EXISTS block (PostgreSQL has no "ADD CONSTRAINT IF NOT EXISTS"), so a
--     re-run against an already-built schema does not error trying to add
--     a duplicate constraint.
--   - Wrapped in one explicit BEGIN ... COMMIT transaction.
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS BL_3NF;

BEGIN;

-- -----------------------------------------------------------------------------
-- Sequences — one per table, per Naming_Conventions.docx ("new sequence for
-- each table")
-- -----------------------------------------------------------------------------
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_PRODUCT_CATEGORY_ID START WITH 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_PRODUCT_TYPE_ID      START WITH 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_PRODUCT_ID           START WITH 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_COUNTRY_ID           START WITH 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CITY_ID              START WITH 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CUSTOMER_ID          START WITH 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_EMPLOYEE_ID          START WITH 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CHANNEL_ID           START WITH 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_PAYMENT_METHOD_ID    START WITH 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_SHIPPING_TYPE_ID     START WITH 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_PAYMENT_TERMS_ID     START WITH 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_SALES_ID             START WITH 1;

-- =============================================================================
-- CE_PRODUCT_CATEGORIES — top of the Product hierarchy (level 1)
-- =============================================================================
CREATE TABLE IF NOT EXISTS BL_3NF.CE_PRODUCT_CATEGORIES
(
    product_category_id    INT             NOT NULL,
    source_id               VARCHAR(50)     NOT NULL,
    source_system           VARCHAR(40)     NOT NULL,
    source_table            VARCHAR(60)     NOT NULL,
    product_category_name   VARCHAR(50)     NOT NULL,
    insert_dt               TIMESTAMP       NOT NULL,
    update_dt               TIMESTAMP,
    CONSTRAINT PK_CE_PRODUCT_CATEGORIES PRIMARY KEY (product_category_id)
);

-- =============================================================================
-- CE_PRODUCT_TYPES — middle of the Product hierarchy (level 2)
-- =============================================================================
CREATE TABLE IF NOT EXISTS BL_3NF.CE_PRODUCT_TYPES
(
    product_type_id         INT             NOT NULL,
    source_id               VARCHAR(50)     NOT NULL,
    source_system           VARCHAR(40)     NOT NULL,
    source_table            VARCHAR(60)     NOT NULL,
    product_type_name       VARCHAR(50)     NOT NULL,
    product_category_id     INT             NOT NULL,
    insert_dt               TIMESTAMP       NOT NULL,
    update_dt               TIMESTAMP,
    CONSTRAINT PK_CE_PRODUCT_TYPES PRIMARY KEY (product_type_id),
    CONSTRAINT FK_PRODUCT_TYPES_2_CATEGORIES FOREIGN KEY (product_category_id)
        REFERENCES BL_3NF.CE_PRODUCT_CATEGORIES (product_category_id)
);

-- =============================================================================
-- CE_PRODUCTS — lowest grain of the Product hierarchy (level 3). One row per
-- SKU, the natural key conformed across B2C and B2B (their local Product IDs
-- are deliberately different for the same physical item). source_id holds
-- the SKU itself, since that — not either source's local Product ID — is
-- what this conformed row is actually keyed on.
-- Warranty/launch year are B2C-context-only; bulk packaging/min order qty
-- are B2B-context-only, so both blocks are nullable on the same conformed
-- row (per the BL_3NF diagram).
-- =============================================================================
CREATE TABLE IF NOT EXISTS BL_3NF.CE_PRODUCTS
(
    product_id               BIGINT          NOT NULL,
    source_id                VARCHAR(20)     NOT NULL,
    source_system            VARCHAR(40)     NOT NULL,
    source_table             VARCHAR(60)     NOT NULL,
    sku                      VARCHAR(20)     NOT NULL,
    product_type_id          INT             NOT NULL,
    brand                    VARCHAR(50)     NOT NULL,
    warranty_period_months   INT,
    launch_year              INT,
    bulk_packaging_unit      VARCHAR(50),
    minimum_order_quantity   INT,
    product_status           VARCHAR(20)     NOT NULL,
    insert_dt                TIMESTAMP       NOT NULL,
    update_dt                TIMESTAMP,
    CONSTRAINT PK_CE_PRODUCTS PRIMARY KEY (product_id),
    CONSTRAINT FK_PRODUCTS_2_PRODUCT_TYPES FOREIGN KEY (product_type_id)
        REFERENCES BL_3NF.CE_PRODUCT_TYPES (product_type_id)
);

-- =============================================================================
-- CE_COUNTRIES — top of the Geography hierarchy (level 1)
-- =============================================================================
CREATE TABLE IF NOT EXISTS BL_3NF.CE_COUNTRIES
(
    country_id        INT             NOT NULL,
    source_id          VARCHAR(100)    NOT NULL,
    source_system      VARCHAR(40)     NOT NULL,
    source_table       VARCHAR(60)     NOT NULL,
    country_name       VARCHAR(100)    NOT NULL,
    insert_dt          TIMESTAMP       NOT NULL,
    update_dt          TIMESTAMP,
    CONSTRAINT PK_CE_COUNTRIES PRIMARY KEY (country_id)
);

-- =============================================================================
-- CE_CITIES — bottom of the Geography hierarchy (level 2, rolls up to Country)
-- =============================================================================
CREATE TABLE IF NOT EXISTS BL_3NF.CE_CITIES
(
    city_id            BIGINT          NOT NULL,
    source_id          VARCHAR(100)    NOT NULL,
    source_system      VARCHAR(40)     NOT NULL,
    source_table       VARCHAR(60)     NOT NULL,
    city_name          VARCHAR(100)    NOT NULL,
    country_id         INT             NOT NULL,
    insert_dt          TIMESTAMP       NOT NULL,
    update_dt          TIMESTAMP,
    CONSTRAINT PK_CE_CITIES PRIMARY KEY (city_id),
    CONSTRAINT FK_CITIES_2_COUNTRIES FOREIGN KEY (country_id)
        REFERENCES BL_3NF.CE_COUNTRIES (country_id)
);

-- =============================================================================
-- CE_EMPLOYEES — NovaTech account managers (B2B only), plus a dedicated
-- "Not Applicable" row (employee_id = 0) every B2C sale points to.
-- =============================================================================
CREATE TABLE IF NOT EXISTS BL_3NF.CE_EMPLOYEES
(
    employee_id         BIGINT          NOT NULL,
    source_id            VARCHAR(60)     NOT NULL,
    source_system        VARCHAR(40)     NOT NULL,
    source_table         VARCHAR(60)     NOT NULL,
    employee_name        VARCHAR(255)    NOT NULL,
    department           VARCHAR(50),
    region_assigned      VARCHAR(50),
    hire_date            DATE,
    email                VARCHAR(255),
    sales_quota          NUMERIC(12,2),
    performance_tier     VARCHAR(20),
    insert_dt            TIMESTAMP       NOT NULL,
    update_dt            TIMESTAMP,
    CONSTRAINT PK_CE_EMPLOYEES PRIMARY KEY (employee_id)
);

-- =============================================================================
-- CE_CHANNELS — junk-style reference table distinguishing the two source
-- systems. No real outside source, so it is built entirely by the ETL
-- (source_system/source_table/source_id = 'MANUAL'/'MANUAL'/'n.a.').
-- =============================================================================
CREATE TABLE IF NOT EXISTS BL_3NF.CE_CHANNELS
(
    channel_id                INT             NOT NULL,
    source_id                  VARCHAR(10)     NOT NULL,
    source_system              VARCHAR(40)     NOT NULL,
    source_table               VARCHAR(60)     NOT NULL,
    channel_name               VARCHAR(10)     NOT NULL,
    originating_system_name    VARCHAR(60)     NOT NULL,
    insert_dt                  TIMESTAMP       NOT NULL,
    update_dt                  TIMESTAMP,
    CONSTRAINT PK_CE_CHANNELS PRIMARY KEY (channel_id)
);

-- =============================================================================
-- CE_PAYMENT_METHODS — B2C only, plus a "Not Applicable" row (id = 0) every
-- B2B sale points to (B2B uses Payment Terms / invoicing instead).
-- =============================================================================
CREATE TABLE IF NOT EXISTS BL_3NF.CE_PAYMENT_METHODS
(
    payment_method_id            INT             NOT NULL,
    source_id                     VARCHAR(20)     NOT NULL,
    source_system                 VARCHAR(40)     NOT NULL,
    source_table                  VARCHAR(60)     NOT NULL,
    payment_method_name           VARCHAR(20)     NOT NULL,
    payment_channel_type          VARCHAR(20),
    processing_fee_percent        NUMERIC(5,2),
    settlement_period_days        INT,
    refundable                    VARCHAR(5),
    currency_accepted             VARCHAR(5),
    minimum_transaction_amount    NUMERIC(10,2),
    availability_channel          VARCHAR(30),
    insert_dt                     TIMESTAMP       NOT NULL,
    update_dt                     TIMESTAMP,
    CONSTRAINT PK_CE_PAYMENT_METHODS PRIMARY KEY (payment_method_id)
);

-- =============================================================================
-- CE_SHIPPING_TYPES — B2C only, plus a "Not Applicable" row (id = 0) every
-- B2B sale points to (B2B doesn't carry a per-line shipping type).
-- =============================================================================
CREATE TABLE IF NOT EXISTS BL_3NF.CE_SHIPPING_TYPES
(
    shipping_type_id                    INT             NOT NULL,
    source_id                            VARCHAR(20)     NOT NULL,
    source_system                        VARCHAR(40)     NOT NULL,
    source_table                         VARCHAR(60)     NOT NULL,
    shipping_type_name                   VARCHAR(20)     NOT NULL,
    shipping_carrier                     VARCHAR(30),
    estimated_delivery_days              VARCHAR(10),
    shipping_cost_tier                   VARCHAR(10),
    free_shipping_eligible               VARCHAR(5),
    tracking_available                   VARCHAR(5),
    max_package_weight_kg                INT,
    international_shipping_available     VARCHAR(5),
    insert_dt                            TIMESTAMP       NOT NULL,
    update_dt                            TIMESTAMP,
    CONSTRAINT PK_CE_SHIPPING_TYPES PRIMARY KEY (shipping_type_id)
);

-- =============================================================================
-- CE_PAYMENT_TERMS — B2B only, plus a "Not Applicable" row (id = 0) every
-- B2C sale points to (B2C pays per transaction, not on terms).
-- =============================================================================
CREATE TABLE IF NOT EXISTS BL_3NF.CE_PAYMENT_TERMS
(
    payment_terms_id              INT             NOT NULL,
    source_id                      VARCHAR(10)     NOT NULL,
    source_system                  VARCHAR(40)     NOT NULL,
    source_table                   VARCHAR(60)     NOT NULL,
    payment_terms_name             VARCHAR(10)     NOT NULL,
    payment_due_days               INT,
    early_payment_discount_pct     NUMERIC(5,2),
    late_payment_penalty_pct       NUMERIC(5,2),
    currency                       VARCHAR(5),
    preferred_payment_method       VARCHAR(20),
    terms_effective_date           DATE,
    insert_dt                      TIMESTAMP       NOT NULL,
    update_dt                      TIMESTAMP,
    CONSTRAINT PK_CE_PAYMENT_TERMS PRIMARY KEY (payment_terms_id)
);

-- =============================================================================
-- CE_CUSTOMERS_SCD — the one Type-2 entity. One row per *version* of a
-- customer or company; customer_id is durable across versions, start_dt
-- disambiguates which version. Tracks account_tier (B2B) and loyalty_member
-- (B2C) history. Individual-only and Business-only attribute blocks are
-- nullable on the same conformed row, same treatment as CE_PRODUCTS.
-- No update_dt: a tracked change is captured as a new row, never an
-- in-place update (Naming_Conventions.docx + this project's own precedent).
-- =============================================================================
CREATE TABLE IF NOT EXISTS BL_3NF.CE_CUSTOMERS_SCD
(
    customer_id          BIGINT          NOT NULL,
    start_dt             TIMESTAMP       NOT NULL,
    source_id            VARCHAR(60)     NOT NULL,
    source_system        VARCHAR(40)     NOT NULL,
    source_table         VARCHAR(60)     NOT NULL,
    customer_type        VARCHAR(10)     NOT NULL,
    customer_name        VARCHAR(255)    NOT NULL,
    date_of_birth        DATE,
    gender               VARCHAR(10),
    loyalty_member       VARCHAR(5),
    customer_segment     VARCHAR(20),
    industry             VARCHAR(50),
    account_tier         VARCHAR(10),
    company_size         VARCHAR(20),
    onboarding_date      DATE,
    credit_limit         NUMERIC(12,2),
    approver_name        VARCHAR(255),
    budget_code          VARCHAR(20),
    city_id              BIGINT          NOT NULL,
    end_dt               TIMESTAMP,
    is_active            BOOLEAN         NOT NULL,
    insert_dt            TIMESTAMP       NOT NULL,
    CONSTRAINT PK_CE_CUSTOMERS_SCD PRIMARY KEY (customer_id, start_dt),
    CONSTRAINT FK_CUSTOMERS_SCD_2_CITIES FOREIGN KEY (city_id)
        REFERENCES BL_3NF.CE_CITIES (city_id)
);

-- =============================================================================
-- CE_SALES — the fact-grain table. One row per order line (Order ID),
-- conformed across both channels. No surrogate-free design here: per this
-- task's brief, every 3NF table (fact included) carries a surrogate key
-- (sales_id), generated by sequence like every other table.
-- customer_id is a logical link only to CE_CUSTOMERS_SCD: per
-- Naming_Conventions.docx, a physical DB FK constraint against an SCD2
-- table is "strongly PROHIBITED", so no FK is declared for that column.
-- Every other FK is NOT NULL, since a "Not Applicable" row always exists
-- on whichever side of the channel split doesn't apply.
-- =============================================================================
CREATE TABLE IF NOT EXISTS BL_3NF.CE_SALES
(
    product_id                  BIGINT          NOT NULL,
    customer_id                 BIGINT          NOT NULL,   -- logical FK only -> CE_CUSTOMERS_SCD (SCD2, no physical FK)
    employee_id                 BIGINT          NOT NULL,
    channel_id                  INT             NOT NULL,
    payment_method_id           INT             NOT NULL,
    shipping_type_id            INT             NOT NULL,
    payment_terms_id            INT             NOT NULL,
    sales_id                    BIGINT          NOT NULL,
    source_id                   VARCHAR(60)     NOT NULL,
    source_system               VARCHAR(40)     NOT NULL,
    source_table                VARCHAR(60)     NOT NULL,
    order_id                    BIGINT          NOT NULL,
    order_date                  DATE            NOT NULL,
    order_status                VARCHAR(20)     NOT NULL,
    quantity                    INT             NOT NULL,
    unit_price                  NUMERIC(10,2)   NOT NULL,
    unit_cost                   NUMERIC(10,2)   NOT NULL,
    total_sales                 NUMERIC(12,2)   NOT NULL,
    total_cost                  NUMERIC(12,2)   NOT NULL,
    rating                      INT,
    add_on_total                NUMERIC(10,2),
    return_or_complaint         VARCHAR(5),
    feedback_comment            VARCHAR(255),
    resolution_time_days        INT,
    refund_amount                NUMERIC(10,2),
    support_channel_used         VARCHAR(10),
    escalation_required          VARCHAR(5),
    po_number                    VARCHAR(20),
    po_issue_date                DATE,
    requested_delivery_date      DATE,
    approval_status               VARCHAR(10),
    po_type                       VARCHAR(10),
    po_value_threshold_flag       VARCHAR(5),
    insert_dt                    TIMESTAMP       NOT NULL,
    CONSTRAINT PK_CE_SALES PRIMARY KEY (sales_id),
    CONSTRAINT FK_SALES_2_PRODUCTS FOREIGN KEY (product_id)
        REFERENCES BL_3NF.CE_PRODUCTS (product_id),
    CONSTRAINT FK_SALES_2_EMPLOYEES FOREIGN KEY (employee_id)
        REFERENCES BL_3NF.CE_EMPLOYEES (employee_id),
    CONSTRAINT FK_SALES_2_CHANNELS FOREIGN KEY (channel_id)
        REFERENCES BL_3NF.CE_CHANNELS (channel_id),
    CONSTRAINT FK_SALES_2_PAYMENT_METHODS FOREIGN KEY (payment_method_id)
        REFERENCES BL_3NF.CE_PAYMENT_METHODS (payment_method_id),
    CONSTRAINT FK_SALES_2_SHIPPING_TYPES FOREIGN KEY (shipping_type_id)
        REFERENCES BL_3NF.CE_SHIPPING_TYPES (shipping_type_id),
    CONSTRAINT FK_SALES_2_PAYMENT_TERMS FOREIGN KEY (payment_terms_id)
        REFERENCES BL_3NF.CE_PAYMENT_TERMS (payment_terms_id)
);

COMMIT;
