-- =============================================================================
-- Business Layer 3NF (schema BL_3NF)
-- =============================================================================
--
-- Conventions applied throughout:
--   - Every surrogate key is generated by its own named SEQUENCE (never SERIAL).
--   - Every table carries a source triplet: source_id (natural key from the
--     source), source_system, source_table.
--   - CE_CUSTOMERS_SCD is the one Type-2 SCD entity: composite PK
--     (customer_id, start_dt), plus end_dt and is_active. No update_dt —
--     a tracked change is captured as a new row, never an in-place update.
--   - CE_SALES carries every FK as NOT NULL. Each channel-specific dimension
--     (e.g. CE_PAYMENT_METHODS for B2C, CE_PAYMENT_TERMS for B2B) has a
--     dedicated "Not Applicable" default row that the other channel points to,
--     so no FK column ever needs to be NULL.
--   - CE_SALES has no physical FK constraint against CE_CUSTOMERS_SCD. A DB
--     FK against an SCD Type-2 table is prohibited because the composite PK
--     (customer_id, start_dt) cannot be the target of a simple FK; the link
--     is logical only, resolved in the DML via a date-range join.
--   - No DEFAULT, UNIQUE, or CHECK constraints anywhere on BL_3NF tables.
--   - CREATE TABLE IF NOT EXISTS / CREATE SEQUENCE IF NOT EXISTS throughout,
--     so the script is fully rerunnable against a schema that already has
--     these objects.
--   - FK constraints are declared inline inside the CREATE TABLE IF NOT
--     EXISTS block, since PostgreSQL has no ADD CONSTRAINT IF NOT EXISTS.
--   - The entire script is wrapped in one explicit BEGIN ... COMMIT.
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS BL_3NF;

BEGIN;

-- -----------------------------------------------------------------------------
-- Sequences — one per table
-- -----------------------------------------------------------------------------
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_PRODUCT_CATEGORY_ID START WITH 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_PRODUCT_TYPE_ID      START WITH 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_PRODUCT_ID           START WITH 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_COUNTRY_ID           START WITH 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CITY_ID              START WITH 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CUSTOMER_ID          START WITH 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_EMPLOYEE_ID          START WITH 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CHANNEL_ID           START WITH 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_PAYMENT_METHOD_ID    START WITH 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_SHIPPING_TYPE_ID     START WITH 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_PAYMENT_TERMS_ID     START WITH 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_SALES_ID             START WITH 1;

-- =============================================================================
-- CE_PRODUCT_CATEGORIES — top of the Product hierarchy (level 1)
-- =============================================================================
CREATE TABLE IF NOT EXISTS BL_3NF.CE_PRODUCT_CATEGORIES
(
    product_category_id    INT             NOT NULL,
    source_id               VARCHAR(50)     NOT NULL,
    source_system           VARCHAR(40)     NOT NULL,
    source_table            VARCHAR(60)     NOT NULL,
    product_category_name   VARCHAR(50)     NOT NULL,
    insert_dt               TIMESTAMP       NOT NULL,
    update_dt               TIMESTAMP,
    CONSTRAINT PK_CE_PRODUCT_CATEGORIES PRIMARY KEY (product_category_id)
);

-- =============================================================================
-- CE_PRODUCT_TYPES — middle of the Product hierarchy (level 2)
-- =============================================================================
CREATE TABLE IF NOT EXISTS BL_3NF.CE_PRODUCT_TYPES
(
    product_type_id         INT             NOT NULL,
    source_id               VARCHAR(50)     NOT NULL,
    source_system           VARCHAR(40)     NOT NULL,
    source_table            VARCHAR(60)     NOT NULL,
    product_type_name       VARCHAR(50)     NOT NULL,
    product_category_id     INT             NOT NULL,
    insert_dt               TIMESTAMP       NOT NULL,
    update_dt               TIMESTAMP,
    CONSTRAINT PK_CE_PRODUCT_TYPES PRIMARY KEY (product_type_id),
    CONSTRAINT FK_PRODUCT_TYPES_2_CATEGORIES FOREIGN KEY (product_category_id)
        REFERENCES BL_3NF.CE_PRODUCT_CATEGORIES (product_category_id)
);

-- =============================================================================
-- CE_PRODUCTS — lowest grain of the Product hierarchy (level 3).
-- One row per SKU, conformed across B2C and B2B. source_id holds the SKU
-- itself as the conforming natural key. warranty_period_months and
-- launch_year are populated from B2C; bulk_packaging_unit and
-- minimum_order_quantity are populated from B2B. Both attribute blocks are
-- nullable on the same conformed row.
-- =============================================================================
CREATE TABLE IF NOT EXISTS BL_3NF.CE_PRODUCTS
(
    product_id               BIGINT          NOT NULL,
    source_id                VARCHAR(20)     NOT NULL,
    source_system            VARCHAR(40)     NOT NULL,
    source_table             VARCHAR(60)     NOT NULL,
    sku                      VARCHAR(20)     NOT NULL,
    product_type_id          INT             NOT NULL,
    brand                    VARCHAR(50)     NOT NULL,
    warranty_period_months   INT,
    launch_year              INT,
    bulk_packaging_unit      VARCHAR(50),
    minimum_order_quantity   INT,
    product_status           VARCHAR(20)     NOT NULL,
    insert_dt                TIMESTAMP       NOT NULL,
    update_dt                TIMESTAMP,
    CONSTRAINT PK_CE_PRODUCTS PRIMARY KEY (product_id),
    CONSTRAINT FK_PRODUCTS_2_PRODUCT_TYPES FOREIGN KEY (product_type_id)
        REFERENCES BL_3NF.CE_PRODUCT_TYPES (product_type_id)
);

-- =============================================================================
-- CE_COUNTRIES — top of the Geography hierarchy (level 1)
-- =============================================================================
CREATE TABLE IF NOT EXISTS BL_3NF.CE_COUNTRIES
(
    country_id        INT             NOT NULL,
    source_id          VARCHAR(100)    NOT NULL,
    source_system      VARCHAR(40)     NOT NULL,
    source_table       VARCHAR(60)     NOT NULL,
    country_name       VARCHAR(100)    NOT NULL,
    insert_dt          TIMESTAMP       NOT NULL,
    update_dt          TIMESTAMP,
    CONSTRAINT PK_CE_COUNTRIES PRIMARY KEY (country_id)
);

-- =============================================================================
-- CE_CITIES — bottom of the Geography hierarchy (level 2, rolls up to Country)
-- =============================================================================
CREATE TABLE IF NOT EXISTS BL_3NF.CE_CITIES
(
    city_id            BIGINT          NOT NULL,
    source_id          VARCHAR(100)    NOT NULL,
    source_system      VARCHAR(40)     NOT NULL,
    source_table       VARCHAR(60)     NOT NULL,
    city_name          VARCHAR(100)    NOT NULL,
    country_id         INT             NOT NULL,
    insert_dt          TIMESTAMP       NOT NULL,
    update_dt          TIMESTAMP,
    CONSTRAINT PK_CE_CITIES PRIMARY KEY (city_id),
    CONSTRAINT FK_CITIES_2_COUNTRIES FOREIGN KEY (country_id)
        REFERENCES BL_3NF.CE_COUNTRIES (country_id)
);

-- =============================================================================
-- CE_EMPLOYEES — NovaTech account managers (B2B only). Every B2C sale
-- points to the "Not Applicable" default row (employee_id = 0).
-- =============================================================================
CREATE TABLE IF NOT EXISTS BL_3NF.CE_EMPLOYEES
(
    employee_id         BIGINT          NOT NULL,
    source_id            VARCHAR(60)     NOT NULL,
    source_system        VARCHAR(40)     NOT NULL,
    source_table         VARCHAR(60)     NOT NULL,
    employee_name        VARCHAR(255)    NOT NULL,
    department           VARCHAR(50),
    region_assigned      VARCHAR(50),
    hire_date            DATE,
    email                VARCHAR(255),
    sales_quota          NUMERIC(12,2),
    performance_tier     VARCHAR(20),
    insert_dt            TIMESTAMP       NOT NULL,
    update_dt            TIMESTAMP,
    CONSTRAINT PK_CE_EMPLOYEES PRIMARY KEY (employee_id)
);

-- =============================================================================
-- CE_CHANNELS — distinguishes the two source systems (B2C / B2B).
-- The channel set is fixed and known in advance, so all rows including the
-- two real channels are seeded in the DML Section A.
-- =============================================================================
CREATE TABLE IF NOT EXISTS BL_3NF.CE_CHANNELS
(
    channel_id                INT             NOT NULL,
    source_id                  VARCHAR(10)     NOT NULL,
    source_system              VARCHAR(40)     NOT NULL,
    source_table               VARCHAR(60)     NOT NULL,
    channel_name               VARCHAR(10)     NOT NULL,
    originating_system_name    VARCHAR(60)     NOT NULL,
    insert_dt                  TIMESTAMP       NOT NULL,
    update_dt                  TIMESTAMP,
    CONSTRAINT PK_CE_CHANNELS PRIMARY KEY (channel_id)
);

-- =============================================================================
-- CE_PAYMENT_METHODS — B2C only. Every B2B sale points to the "Not
-- Applicable" default row (payment_method_id = 0) because B2B uses
-- invoicing terms rather than a per-transaction payment method.
-- =============================================================================
CREATE TABLE IF NOT EXISTS BL_3NF.CE_PAYMENT_METHODS
(
    payment_method_id            INT             NOT NULL,
    source_id                     VARCHAR(20)     NOT NULL,
    source_system                 VARCHAR(40)     NOT NULL,
    source_table                  VARCHAR(60)     NOT NULL,
    payment_method_name           VARCHAR(20)     NOT NULL,
    payment_channel_type          VARCHAR(20),
    processing_fee_percent        NUMERIC(5,2),
    settlement_period_days        INT,
    refundable                    VARCHAR(5),
    currency_accepted             VARCHAR(5),
    minimum_transaction_amount    NUMERIC(10,2),
    availability_channel          VARCHAR(30),
    insert_dt                     TIMESTAMP       NOT NULL,
    update_dt                     TIMESTAMP,
    CONSTRAINT PK_CE_PAYMENT_METHODS PRIMARY KEY (payment_method_id)
);

-- =============================================================================
-- CE_SHIPPING_TYPES — B2C only. Every B2B sale points to the "Not
-- Applicable" default row (shipping_type_id = 0) because B2B orders do
-- not carry a per-line shipping type in this dataset.
-- =============================================================================
CREATE TABLE IF NOT EXISTS BL_3NF.CE_SHIPPING_TYPES
(
    shipping_type_id                    INT             NOT NULL,
    source_id                            VARCHAR(20)     NOT NULL,
    source_system                        VARCHAR(40)     NOT NULL,
    source_table                         VARCHAR(60)     NOT NULL,
    shipping_type_name                   VARCHAR(20)     NOT NULL,
    shipping_carrier                     VARCHAR(30),
    estimated_delivery_days              VARCHAR(10),
    shipping_cost_tier                   VARCHAR(10),
    free_shipping_eligible               VARCHAR(5),
    tracking_available                   VARCHAR(5),
    max_package_weight_kg                INT,
    international_shipping_available     VARCHAR(5),
    insert_dt                            TIMESTAMP       NOT NULL,
    update_dt                            TIMESTAMP,
    CONSTRAINT PK_CE_SHIPPING_TYPES PRIMARY KEY (shipping_type_id)
);

-- =============================================================================
-- CE_PAYMENT_TERMS — B2B only. Every B2C sale points to the "Not
-- Applicable" default row (payment_terms_id = 0) because B2C customers
-- pay per transaction rather than on invoicing terms.
-- =============================================================================
CREATE TABLE IF NOT EXISTS BL_3NF.CE_PAYMENT_TERMS
(
    payment_terms_id              INT             NOT NULL,
    source_id                      VARCHAR(10)     NOT NULL,
    source_system                  VARCHAR(40)     NOT NULL,
    source_table                   VARCHAR(60)     NOT NULL,
    payment_terms_name             VARCHAR(10)     NOT NULL,
    payment_due_days               INT,
    early_payment_discount_pct     NUMERIC(5,2),
    late_payment_penalty_pct       NUMERIC(5,2),
    currency                       VARCHAR(5),
    preferred_payment_method       VARCHAR(20),
    terms_effective_date           DATE,
    insert_dt                      TIMESTAMP       NOT NULL,
    update_dt                      TIMESTAMP,
    CONSTRAINT PK_CE_PAYMENT_TERMS PRIMARY KEY (payment_terms_id)
);

-- =============================================================================
-- CE_CUSTOMERS_SCD — SCD Type-2 entity. One row per version of a customer
-- or company. customer_id is durable across versions; start_dt
-- disambiguates which version is active. Tracked attributes: loyalty_member
-- (B2C) and account_tier (B2B). Individual-only and Business-only attribute
-- blocks are nullable on the same conformed row, mirroring CE_PRODUCTS.
-- No update_dt: a change in a tracked attribute produces a new row and
-- closes the previous one; nothing is updated in place.
-- =============================================================================
CREATE TABLE IF NOT EXISTS BL_3NF.CE_CUSTOMERS_SCD
(
    customer_id          BIGINT          NOT NULL,
    start_dt             TIMESTAMP       NOT NULL,
    source_id            VARCHAR(60)     NOT NULL,
    source_system        VARCHAR(40)     NOT NULL,
    source_table         VARCHAR(60)     NOT NULL,
    customer_type        VARCHAR(10)     NOT NULL,
    customer_name        VARCHAR(255)    NOT NULL,
    date_of_birth        DATE,
    gender               VARCHAR(10),
    loyalty_member       VARCHAR(5),
    customer_segment     VARCHAR(20),
    industry             VARCHAR(50),
    account_tier         VARCHAR(10),
    company_size         VARCHAR(20),
    onboarding_date      DATE,
    credit_limit         NUMERIC(12,2),
    approver_name        VARCHAR(255),
    budget_code          VARCHAR(20),
    city_id              BIGINT          NOT NULL,
    end_dt               TIMESTAMP,
    is_active            BOOLEAN         NOT NULL,
    insert_dt            TIMESTAMP       NOT NULL,
    CONSTRAINT PK_CE_CUSTOMERS_SCD PRIMARY KEY (customer_id, start_dt),
    CONSTRAINT FK_CUSTOMERS_SCD_2_CITIES FOREIGN KEY (city_id)
        REFERENCES BL_3NF.CE_CITIES (city_id)
);

-- =============================================================================
-- CE_SALES — the fact-grain table. One row per order line, conformed across
-- both channels. Every FK column is NOT NULL; channel-specific FKs that do
-- not apply resolve to the corresponding dimension's default row (id = 0).
-- customer_id is a logical link to CE_CUSTOMERS_SCD only — no physical FK
-- constraint is declared because an FK against an SCD Type-2 composite PK
-- is not supported; the correct historical version is resolved in the DML
-- via a date-range join on start_dt / end_dt.
-- =============================================================================
CREATE TABLE IF NOT EXISTS BL_3NF.CE_SALES
(
    product_id                  BIGINT          NOT NULL,
    customer_id                 BIGINT          NOT NULL,   -- logical FK only -> CE_CUSTOMERS_SCD (no physical FK on SCD2)
    employee_id                 BIGINT          NOT NULL,
    channel_id                  INT             NOT NULL,
    payment_method_id           INT             NOT NULL,
    shipping_type_id            INT             NOT NULL,
    payment_terms_id            INT             NOT NULL,
    sales_id                    BIGINT          NOT NULL,
    source_id                   VARCHAR(60)     NOT NULL,
    source_system               VARCHAR(40)     NOT NULL,
    source_table                VARCHAR(60)     NOT NULL,
    order_id                    BIGINT          NOT NULL,
    order_date                  DATE            NOT NULL,
    order_status                VARCHAR(20)     NOT NULL,
    quantity                    INT             NOT NULL,
    unit_price                  NUMERIC(10,2)   NOT NULL,
    unit_cost                   NUMERIC(10,2)   NOT NULL,
    total_sales                 NUMERIC(12,2)   NOT NULL,
    total_cost                  NUMERIC(12,2)   NOT NULL,
    rating                      INT,
    add_on_total                NUMERIC(10,2),
    return_or_complaint         VARCHAR(5),
    feedback_comment            VARCHAR(255),
    resolution_time_days        INT,
    refund_amount                NUMERIC(10,2),
    support_channel_used         VARCHAR(10),
    escalation_required          VARCHAR(5),
    po_number                    VARCHAR(20),
    po_issue_date                DATE,
    requested_delivery_date      DATE,
    approval_status               VARCHAR(10),
    po_type                       VARCHAR(10),
    po_value_threshold_flag       VARCHAR(5),
    insert_dt                    TIMESTAMP       NOT NULL,
    CONSTRAINT PK_CE_SALES PRIMARY KEY (sales_id),
    CONSTRAINT FK_SALES_2_PRODUCTS FOREIGN KEY (product_id)
        REFERENCES BL_3NF.CE_PRODUCTS (product_id),
    CONSTRAINT FK_SALES_2_EMPLOYEES FOREIGN KEY (employee_id)
        REFERENCES BL_3NF.CE_EMPLOYEES (employee_id),
    CONSTRAINT FK_SALES_2_CHANNELS FOREIGN KEY (channel_id)
        REFERENCES BL_3NF.CE_CHANNELS (channel_id),
    CONSTRAINT FK_SALES_2_PAYMENT_METHODS FOREIGN KEY (payment_method_id)
        REFERENCES BL_3NF.CE_PAYMENT_METHODS (payment_method_id),
    CONSTRAINT FK_SALES_2_SHIPPING_TYPES FOREIGN KEY (shipping_type_id)
        REFERENCES BL_3NF.CE_SHIPPING_TYPES (shipping_type_id),
    CONSTRAINT FK_SALES_2_PAYMENT_TERMS FOREIGN KEY (payment_terms_id)
        REFERENCES BL_3NF.CE_PAYMENT_TERMS (payment_terms_id)
);

COMMIT;
